### ISSUE TITLE
simplify issue labels

### ISSUE THREAD

**Issue by Huex** [allan-walpy/vulmy#16]
Считаю что ":// и до" можно убрать, у меня мозг чуть не сломался, когда увидел доску и ишуи

**Comment by allan-walpy** [comment]
- тип issue [prefix `.`]
  - `.bug` - репорт на баг;
  - `.feature` - запрос на новую фичу;
  - `.refactor` - указание на синтаксические ошибки, ошибки в коде, предложения по улучшению приложения, его быстродействия и т.д.;
  - `.question` - запрос на информацию - по решению проблем на стороне пользователей приложения (если классификации выше пока не могут быть выданы);

- этап issue [prefix `/`]
  - `/info` - необходима дополнительная информация:
    - для багов - установить в чем причина;
    - для feature - проанализировать что нужно сделать для issue;
    - для refactor - узнать действительно ли предложение улучшит приложение (или возымеет эффект что обещает);
    - для question - говорит об открытой дискуссии issue;
  - `/invalid` - issue отклонено:
    - для багов - не является багом;
    - для feature - фича в данном виде не будет запилена;
    - для refactor - рефактор признан разрушительным или несоответствующим Convention Code;
  - `/hold` - issue временно приостановлено - для его реализации необходимы условия которых пока нет но появятся в будущем (особенно часто при зависимости issue от других issue);
 
- важность issue [prefix `_`] //над названиями поработать
  - `_black` - важность не установлена или не может быть присуждена на данном этапе;
  -  `_green` - важность обычная:
     - для багов - не критический баг, сильно не разрушающий функциональность;
     - для feature - не самая важная функциональность;
     - для refactor - не самое необходимое предложение в данный момент;
  - `_yellow` - важность средняя;
    - для багов - баг сильно нарушающий работу части функционала;
    - для feature - необходимая фича;
    - для refactor - данные предложения лучше реализовать для уменьшения технического долга;
  - `_red` - важность высокая;
    - для багов - баг сильно нарушающий работу обширной части функционала;
    - для feature - фича без которой не возможно нормальное (запланированное )использование приложения;
     - для refactor - имеются большие проблемы в коде, что лучше немедленно решить, прежде чем продолжать работу;
  - `_fatal` - важность чрезвычайная;
     - для багов - приложение не запускается/компилируется/не работает совсем;
     - для feature - это не фича - это основная задача приложения;
     - для refactor - имеющийся технический долг приводит к многочисленным багам (в том числе и возможным);

- область распространения issue [prefix `:`]
  - `:repository` - какие либо файлы репозитория, расположения в нем папок и т.д. (в том числе isuue по docs);
  - `:project` - затрагивает solution в целом или связи между проектами;
  - `:server` - затрагивает Vulmy.Server проект;

**Comment by Huex** [comment]
## Мое предложение
Использовать Issues как трекер задач и площадки решения различных вопросов. А для workflow использовать доски Github - Projects
### Labels
- Bug - Ошибка в продукте
- Improvement - Улучшение существующиего функционал
- New Feature - Запрос на новый функционал
- Task - Задача, которая должна быть выполнена (может быть Bug, Improvement, New Feature)
- Suggestion - Предложение (может быть Bug, Improvement, New Feature)


Поясняю по workflow, после того как предложение было рассмотрено выдвигают два решения: реализовывать или закрыть Issue. Если реализовывать то меняем Suggestion на Task, или создаем новое Issue уже с пометкой Task и привязкой к исходному Suggestion Issue. И отправляем это Task Issue на доску для реализации.

**Comment by allan-walpy** [comment]
- тип issue [prefix `.`]
  - `.bug` - баг репорт;
  - `.improvement` - улучшение существующего функционала;
  - `.feature` - запрос на новый функционал;
  - `.question` - вопрос или обсуждение;

- этап issue [prefix `/`]
  - `/suggestion` - предложение:
    - для багов - предположение о новом баге;
    - для improvement - предложение об улучшении имеющегося кода;
    - для feature - предложение о внесении нового функционала;
  - `/task` - для одобренных issue;
   - для багов - наличие бага подтверждено;
   - для improvement - предложение будет исполнена;
   - для feature - функционал будет добавлен;
  - `/hold` - issue временно приостановлено;
  - `/closed` - issue закрыто;
 
- важность issue [prefix `_`] //над названиями поработать
  -  `_green` - важность обычная:
  - `_yellow` - важность средняя;
  - `_red` - важность высокая;
  - `_fatal` - важность чрезвычайная, приложение не работает/крашится/не компилируется;

- область распространения issue [prefix `:`]
   - `:repository` - какие либо файлы репозитория, расположения в нем папок и т.д. (в том числе isuue по docs);
   - `:project` - затрагивает solution в целом или связи между проектами;
   - `:server` - затрагивает Vulmy.Server проект;

- причина issue [prefix `!`] только для `/closed` или `/hold` issue;
   - `!done` для [*] - выполнено (в случае бага - исправлено, в случае question - дискуссия завершена/вопрос решён);
  - `!duplicate` для [*] - такое issue уже есть;
  - `!incomplete` для [*] - недостаточно информации для дальнейшей работы;
  - `!cannotReproduce` для [bug] - баг невозможно воспроизвести;
  - `!wontFix` для [bug] - не будет выполнено: баг был зарегистрирован, но в новой версии не повторяется;

**Comment by allan-walpy** [comment]
## Labels

### тип issue [prefix `.`] для любого issue;

  - `.bug` - запрос на исправление бага;
  - `.improvement` - запрос на улучшение;
  - `.new feature` - запрос на новый функционал;
  - `.question` - вопрос или обсуждение;

### этап issue [prefix `/`] для bug, improvement, feature;

  - `/suggestion` - внесение предложения;
  - `/task` - предложение обговорено и одобрено и к нему можно приступить;
 
### важность issue [prefix `_`] для bug, improvement, feature;

  -  `_green` - важность обычная:
  - `_yellow` - важность средняя;
  - `_red` - важность высокая;

### область распространения issue [prefix `:`]

  - `:repository` - какие либо файлы репозитория, расположения в нем папок и т.д. (в том числе isuue по docs);
  - `:project` - затрагивает solution в целом или связи между проектами;
  - `:server` - затрагивает Vulmy.Server проект;

### причина issue [prefix `!`] только для закрытых issue;

  - `!reject` для [ suggestion:* ] - не одобрено, подробности могут быть в комментарии к закрытию issue;
   - `!done` для [ task:*, question ] - выполнено (в случае бага - исправлено, в случае question - дискуссия завершена/вопрос решён);
  - `!duplicate` для [ task:*] - такое issue уже есть;
  - `!incomplete` для [*:bug,feature] - недостаточно информации для дальнейшей работы;
  - `!cannotReproduce` для [ suggestion:bug ] - баг невозможно воспроизвести;
  - `!wontFix` для [ task:bug ] - не будет исправлено: баг в старой версии есть, но в новой версии не повторяется;

## Workflow

Вносится предложение. Его рассматривают и дают решение - об отклонении или одобрении с последующей передаче в Task. Если передано в таск - issue оказывается на доске.

**Comment by Huex** [comment]
## Labels
### Обязательные

Тип
  - `is bug` - ошибка
  - `is improvement` - улучшение
  - `is feature` - новый функционал
  - `is question` - вопрос, обсуждение

Этап
  - `flow suggestion` - предложение
  - `flow task` - задача
 
### Рекомендуются

Важность
  - `alert green` - незначительная потеря функциональности
  - `alert yellow` - существенная потеря функциональности
  - `alert red` - серьёзная проблема в работе

Область, к которой относится Issue
  - `scope project` - затрагивает всё решение
  - `scope server` - затрагивает Vulmy.Server

Итог, при за закрытии Issue
  - `cause invalid` - не одобрено
  - `cause done` - выполнено/решено
  - `cause duplicate` - такое Issue уже существует
  - `cause incomplete` - недостаточно информации
  - `cause cannot reproduce` - невозможно воспроизвести
  - `cause won't done` - не будет выполнено, подробности должны быть указаны в комментарии
  - `cause won't fix` - не будет исправлено, решено в новой версии
