### ISSUE TITLE
choose framework for logging and add logs

### ISSUE THREAD

**Issue by Huex** [allan-walpy/vulmy#20]
Examples: https://github.com/NLog/NLog/tree/dev/examples
Page: https://nlog-project.org/

**Comment by allan-walpy** [comment]
todo: compare default logging, NLog and look up for alternatives

requirements for candidates:
 - support of .net core 2.x;
 - popularity among coders (at least 100k/500k total downloads on nuget);
 - simplicity in using;
 - posibility adding logfiles;
 - log filters (log for errors, log for warnings, trace logs - which could be enabled/disabled on demand - even in runtime);

**Comment by allan-walpy** [comment]
interesting [article](https://stackify.com/asp-net-core-logging-what-changed/), mentioning three third side logging frameworks - can start from here

**Comment by allan-walpy** [comment]
| Framework | 
|------------------:|
|native          |

p.s. table will be populated when time passes, see later for updates

**Comment by allan-walpy** [comment]
sticking with `NLog` so far

**Comment by allan-walpy** [comment]
according to [framework](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) and [netstandard page](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) - we need net standard 2.0

**Comment by allan-walpy** [comment]
seems all ok,I will proceed in #10 with NLog for Asp.Net Core 2
